name: CI

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@a6e26b22319003294c58386b6f25edbc7336819a # v1.18.0
        with:
          otp-version: 26
          elixir-version: 1.18
      - run: cd neurow && mix format --check-formatted
      - run: cd neurow && mix deps.get
      - run: cd neurow && mix compile --warnings-as-errors
      - run: epmd -daemon
      - run: cd neurow && mix test

  ci-loadtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@a6e26b22319003294c58386b6f25edbc7336819a # v1.18.0
        with:
          otp-version: 26
          elixir-version: 1.18
      - run: cd load_test && mix format --check-formatted
      - run: cd load_test && mix deps.get
      - run: cd load_test && mix compile --warnings-as-errors

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          cd neurow
          docker build . -t neurow:${{ github.sha }}
          docker run -e JWT_CONFIG="{\"local_name\":\"neurow\",\"service_name\":\"neurow\",\"algorithm\":\"HS256\",\"clients\":{\"test\":\"secret\"}}" -d --name neurow_${{ github.sha }}_test neurow:${{ github.sha }}
          docker exec neurow_${{ github.sha }}_test curl -v --retry 5 --retry-connrefused --retry-max-time 30 --retry-delay 6 http://localhost:3000/ping 
          docker stop neurow_${{ github.sha }}_test
          docker rm neurow_${{ github.sha }}_test

  docker_load_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          cd load_test
          docker build . -t neurow:${{ github.sha }}
