name: Docker push

permissions:
  contents: read
  id-token: write

on:
  push:
    branches:
      - main

jobs:
  docker_push:
    runs-on: prod-linux-s
    steps:
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a # v 4.0.1
        with:
          role-to-assume: ${{ secrets.iam_role }}
          role-session-name: docker_build_public
          aws-region: us-east-1

      - uses: actions/checkout@v4

      - run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/doctolib
          cd neurow
          docker buildx build . --build-arg GIT_COMMIT_SHA1=${{ github.event.pull_request.head.sha || github.event.after || github.sha }} --push -t public.ecr.aws/doctolib/neurow:latest -t public.ecr.aws/doctolib/neurow:latest -t public.ecr.aws/doctolib/neurow:${{ github.event.pull_request.head.sha || github.event.after || github.sha }}
